services:
  postgres:
    image: postgres
    container_name: prs_food
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prs_food
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
